const agendaToursConfig = {
  header: {
    title: 'Mis tours',
    description: 'Crea tours, administra horarios y controla tus reservas desde un solo lugar.',
    addTourButton: 'Agregar tour',
    loadingText: 'Cargando tours...',
    emptyText: 'Todavia no has creado tours. Usa "Agregar tour" para crear el primero.',
    archivedTitle: 'Tours inactivos o vencidos',
    archivedDescription: 'Estos tours ya no aceptan agendas nuevas.',
    helpTitle: 'Como funcionan los tours y sus horarios',
    helpText: [
      'Los tours y sus horarios son publicos en tu pagina mientras estan disponibles.',
      'Cuando pulsas un horario disponible y agregas una agenda, ese horario deja de ser publico y ya no aparece para los demas.',
      'Ese horario reservado solo podras verlo y administrarlo tu desde este panel.',
    ],
  },
  tourCard: {
    untitledTour: 'Sin titulo',
    emptyDetails: 'Sin detalles adicionales.',
    viewTour: 'Ver',
    editTour: 'Editar tour',
    deleteTour: 'Eliminar tour',
    scheduleTitle: 'Horarios',
    emptySchedule: 'No hay horarios configurados.',
    archivedScheduleText: 'Este tour ya no muestra horarios porque esta inactivo o su fecha ya paso.',
    noLocations: 'Sin ubicaciones',
    noPlace: 'Sin lugar',
    noContact: 'Sin contacto',
    noDetail: 'Sin detalle',
    labels: {
      locations: 'Ubicaciones',
      details: 'Detalles del tour',
      place: 'Lugar',
      contact: 'Contacto',
      channel: 'Canal',
      time: 'Horario',
      detail: 'Detalle',
    },
    actions: {
      openLocation: 'Abrir ubicacion',
      addReservation: 'Agregar agenda',
      addReservationHelpTitle: 'Como funciona la agenda del horario',
      addReservationHelpText: [
        'Al agregar una agenda en un horario disponible, ese espacio deja de mostrarse al publico.',
        'La reserva del horario solo la veras tu dentro del panel para administrarla con privacidad.',
      ],
      viewReservation: 'Ver agenda',
      editReservation: 'Editar agenda',
      openContact: 'Abrir contacto',
      deleteReservation: 'Eliminar agenda',
    },
  },
  tourModal: {
    addTitle: 'Agregar tour',
    editTitle: 'Editar tour',
    description: 'Selecciona una fecha en el calendario, define tus horarios y guarda el tour.',
    closeButton: 'Cerrar',
    fields: {
      title: 'Titulo',
      date: 'Fecha',
      active: 'Tour activo',
      details: 'Detalles',
      mapsLocation: 'Ubicaciones',
      mapsPlaceholder: 'Una ubicacion por linea',
    },
    schedulesTitle: 'Horarios disponibles',
    schedulesCaption: 'Se muestran en 12 horas, pero se guardan en formato 24 horas.',
    removeSlot: 'Quitar',
    saveCreate: 'Crear tour',
    saveEdit: 'Guardar cambios',
    saving: 'Guardando...',
    cancel: 'Cancelar',
  },
  reservationModal: {
    addTitle: 'Nueva agenda',
    editTitle: 'Editar agenda',
    closeButton: 'Cerrar',
    fields: {
      place: 'Lugar',
      placePlaceholder: 'Lugar o punto de encuentro',
      contact: 'Numero o usuario',
      contactPlaceholder: 'Telefono o usuario',
      channel: 'Canal',
      detail: 'Detalle',
      detailPlaceholder: 'Notas adicionales para esta reserva',
    },
    saveCreate: 'Guardar agenda',
    saveEdit: 'Guardar cambios',
    saving: 'Guardando...',
    cancel: 'Cancelar',
  },
  confirmModal: {
    closeButton: 'Cerrar',
    cancel: 'Cancelar',
    processing: 'Procesando...',
    deleteTourTitle: 'Eliminar tour',
    deleteTourLabel: 'Eliminar tour',
    deleteAgendaTitle: 'Eliminar agenda',
    deleteAgendaLabel: 'Eliminar agenda',
  },
  messages: {
    deleteTourMessage: (tourTitle) => `Se eliminara el tour "${tourTitle}" y todas sus agendas reservadas.`,
    deleteAgendaMessage: (placeName) => `Se eliminara la agenda de ${placeName} y el horario volvera a quedar disponible.`,
  },
};

export default agendaToursConfig;