const rifasConfig = {
  header: {
    title: 'Mis rifas',
    description: 'Crea rifas, revisa numeros disponibles y registra compras privadas.',
    addButton: 'Agregar rifa',
    loadingText: 'Cargando rifas...',
    emptyText: 'Todavia no has creado rifas.',
    activeSection: 'Rifas activas',
    archivedSection: 'Rifas vencidas o desactivadas',
    archivedEmptyText: 'No hay rifas vencidas o desactivadas.',
    helpTitle: 'Como funcionan las rifas y los numeros apartados',
    helpText: [
      'Las rifas y los numeros disponibles pueden mostrarse en tu pagina publica.',
      'Cuando registras un numero como comprado, ese numero deja de verse como disponible para los demas.',
      'Los datos privados de la compra solo los ves y administras tu desde este panel.',
    ],
  },
  card: {
    untitled: 'Sin titulo',
    emptyDetails: 'Sin detalles.',
    drawDate: 'Sorteo',
    drawTime: 'Hora',
    createdDate: 'Creada',
    status: 'Estado',
    activeStatus: 'Activa',
    inactiveStatus: 'Desactivada',
    expiredStatus: 'Vencida',
    soldOutStatus: 'Agotada',
    price: 'Precio',
    totalNumbers: 'Numeros',
    availableTitle: 'Numeros',
    numberLegend: 'Toca un numero para marcarlo. Toca una X para contactar, editar o borrar la compra.',
    purchasedTitle: 'Comprados',
    noPurchased: 'Todavia no hay numeros comprados.',
    placeFallback: 'Sin lugar',
    detailFallback: 'Sin detalles',
    labels: {
      place: 'Lugar',
      contact: 'Contacto',
      channel: 'Canal',
      detail: 'Detalle',
      prizes: 'Premios',
      winners: 'Ganadores',
      terms: 'Terminos',
    },
    actions: {
      view: 'Ver',
      edit: 'Editar',
      delete: 'Eliminar',
    },
  },
  createModal: {
    title: 'Crear rifa',
    editTitle: 'Editar rifa',
    close: 'Cerrar',
    save: 'Guardar rifa',
    saveEdit: 'Guardar cambios',
    saving: 'Guardando...',
    cancel: 'Cancelar',
    fields: {
      title: 'Titulo',
      details: 'Detalles',
      drawDate: 'Fecha del sorteo',
      drawTime: 'Hora del sorteo',
      price: 'Precio por numero',
      totalNumbers: 'Total de numeros',
      terms: 'Terminos y condiciones',
      prizes: 'Premios',
      winners: 'Ganadores',
      multilineHelp: 'Escribe una linea por item.',
      enabled: 'Rifa activa',
    },
  },
  purchaseModal: {
    title: 'Anotar comprado',
    editTitle: 'Editar comprado',
    close: 'Cerrar',
    save: 'Guardar compra',
    saveEdit: 'Guardar cambios',
    delete: 'Borrar compra',
    saving: 'Guardando...',
    cancel: 'Cancelar',
    fields: {
      place: 'Lugar',
      placePlaceholder: 'Lugar del comprador',
      contact: 'Numero o usuario',
      contactPlaceholder: 'Telefono o usuario',
      channel: 'Canal',
      detail: 'Detalles',
      detailPlaceholder: 'Forma de pago o notas',
    },
  },
  occupiedActions: {
    title: 'Numero ocupado',
    close: 'Cerrar',
    view: 'Ver',
    contact: 'Contactar',
    edit: 'Editar',
    delete: 'Eliminar',
  },
  occupiedView: {
    title: 'Detalle del numero',
    close: 'Cerrar',
    labels: {
      number: 'Numero',
      place: 'Lugar',
      contact: 'Contacto',
      channel: 'Canal',
      detail: 'Detalle',
    },
  },
  confirm: {
    deleteRifaTitle: 'Eliminar rifa',
    deleteRifaLabel: 'Eliminar rifa',
    deleteCompraTitle: 'Eliminar compra',
    deleteCompraLabel: 'Eliminar compra',
    cancel: 'Cancelar',
    close: 'Cerrar',
    processing: 'Procesando...',
  },
};

export default rifasConfig;